#!/usr/bin/env bash

# set -e
script="${0}"
script_cmd="${script}3.py"
script_base=$(basename "$script")
### BEGIN INIT INFO
# Provides:          systemctl3.py service
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Systemctl3.py front-end script in Termux.
### END INIT INFO

# Must be a valid filename
NAME=systemctl-init
PIDDIR=$PREFIX/var/run
PIDFILE=$PIDDIR/$NAME.pid
#This is the command to be run, give the full pathname
DAEMON=$PREFIX/bin/runsvdir
DAEMON_OPTS="$SVDIR"

systemd(){
  case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        restart
        ;;
    status)
        status
        ;;
    *)
        echo "Usage: $0 {start|stop|restart|status}"
        exit 1
        ;;
  esac
}

control(){
  [ ! -x /usr/bin/python3 ] && command="termux-chroot $command"
  $command ${@}
}

systemctl(){
  [ "$1" = "reboot" ] && systemd restart && return 0
  if [ "$EUID" -eq 0 ] || [ -n "${TERMUX_VERSION}" ] ; then
    command="$script_cmd"
  elif sudo_path=$(which sudo); then
    command="$sudo_path $script_cmd"
  else
    echo -e "\033[0;31mCall to systemctl ${@} may fail: Interactive authentication required.\033[0m"
    command="$script_cmd"
  fi
  control ${@}
}

journalctl(){ 
  control ${@} 
}

case $script_base in
  systemctl)
    systemctl ${@}
    ;;
  journalctl)
    journalctl ${@}
    ;;
  systemd|service)
    systemd ${@}
    ;;
  init|*.sh)
    systemd start
    ;;
  reboot)
    systemd restart
    ;;
  halt)
    systemd stop
    ;;
  *)
    echo ${script_base}: applet not found
    exit 1
    ;;
esac
